<?xml version="1.0"?>
<package format="3">
  <name>turtle_custom_interface_py</name>
  <version>0.0.0</version>
  <description>DrawPolygon action server + WaypointList publisher (py only, separate for submission)</description>
  <maintainer email="visualkhh@gmail.com">pa</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>turtle_interfaces</depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
