<?xml version="1.0"?>
<package format="3">
  <name>turtle_cpp_full_bringup</name>
  <version>0.0.0</version>
  <description>bringup launch for turtlesim + turtle_cpp (C++ port)</description>
  <maintainer email="visualkhh@gmail.com">pa</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>turtlesim</exec_depend>
  <exec_depend>turtle_cpp</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
