<?xml version="1.0"?>
<package format="3">
  <name>turtle_cpp</name>
  <version>0.0.0</version>
  <description>turtle_cpp nodes (rclcpp port of turtle_py)</description>
  <maintainer email="visualkhh@gmail.com">pa</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>turtlesim</depend>
  <depend>geometry_msgs</depend>
  <depend>std_srvs</depend>
  <depend>rclcpp_action</depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
